name: inventory_management_system
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_svg: 0.18.1
  simple_animations: 2.2.1
  animated_bottom_navigation_bar: ^0.1.2+2
  provider: ^4.3.2+2
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase: ^7.3.0
  firebase_core: ^0.5.0
  google_sign_in: ^4.5.3
  getx_generator: ^0.0.43
  get: ^3.10.2
  google_fonts: ^1.1.0
  barcode_scan: ^3.0.1
  bloc: ^6.0.3
  image_cropper: ^1.3.1
  firebase_storage: ^4.0.0
  image_picker: ^0.6.7+11
  circular_profile_avatar: ^1.0.6
  sqflite: ^1.3.1+1
  flutter_rounded_progress_bar: ^0.1.2
  cached_network_image: 2.3.2
  focused_menu: 1.0.1
  flutter_gradients: ^1.0.0+2
  bottom_navy_bar: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

